import { test, expect } from '@playwright/test';
import { registerUser } from './helpers';

/**
 * Settings page E2E tests — theme switching, locale, and household invite code.
 *
 * Each test registers a fresh user so tests are independent and parallelisable.
 *
 * Requires:
 *   docker compose --profile dev up -d
 *   cd frontend && bun run test:e2e
 */

test.describe('Settings — page loads', () => {
    test('settings page renders with the correct title and heading', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page).toHaveTitle(/Settings/i);

        // The page renders <h1 class="page-title">Settings</h1>
        await expect(page.getByRole('heading', { name: 'Settings', level: 1 })).toBeVisible({ timeout: 10_000 });
    });

    test('settings page shows section headings for Language and Theme', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // <h2 class="section-title">Language</h2> and Theme
        await expect(page.getByRole('heading', { name: 'Language', level: 2 })).toBeVisible({ timeout: 10_000 });
        await expect(page.getByRole('heading', { name: 'Theme', level: 2 })).toBeVisible();
    });
});

test.describe('Settings — theme', () => {
    test('Dark, Light, and System theme buttons are visible', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.getByRole('button', { name: 'Dark' })).toBeVisible({ timeout: 10_000 });
        await expect(page.getByRole('button', { name: 'Light' })).toBeVisible();
        await expect(page.getByRole('button', { name: 'System' })).toBeVisible();
    });

    test('clicking Dark theme button applies data-theme="dark" to <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.getByRole('button', { name: 'Dark' })).toBeVisible({ timeout: 10_000 });
        await page.getByRole('button', { name: 'Dark' }).click();

        // The settings page sets data-theme on document.documentElement (<html>)
        await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark', { timeout: 5_000 });
    });

    test('clicking Light theme button applies data-theme="light" to <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.getByRole('button', { name: 'Light' })).toBeVisible({ timeout: 10_000 });
        await page.getByRole('button', { name: 'Light' }).click();

        await expect(page.locator('html')).toHaveAttribute('data-theme', 'light', { timeout: 5_000 });
    });

    test('clicking System theme button removes data-theme attribute from <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // First switch to dark so there is something to clear
        await expect(page.getByRole('button', { name: 'Dark' })).toBeVisible({ timeout: 10_000 });
        await page.getByRole('button', { name: 'Dark' }).click();
        await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark', { timeout: 5_000 });

        // Now switch to System
        await page.getByRole('button', { name: 'System' }).click();
        await expect(page.locator('html')).not.toHaveAttribute('data-theme', { timeout: 5_000 });
    });
});

test.describe('Settings — household invite code', () => {
    test('invite code is displayed after registration', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // The household section renders the invite code in .invite-code-value
        const inviteCodeValue = page.locator('.invite-code-value');
        await expect(inviteCodeValue).toBeVisible({ timeout: 10_000 });

        // The invite code generated by the backend should not be empty
        const code = await inviteCodeValue.textContent();
        expect(code).toBeTruthy();
        expect((code ?? '').trim().length).toBeGreaterThan(0);
    });

    test('invite code section shows the household name "E2E Household"', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // The household name used during registration was "E2E Household"
        await expect(page.getByText('E2E Household')).toBeVisible({ timeout: 10_000 });
    });

    test('Copy button is present next to the invite code', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.locator('.invite-code-value')).toBeVisible({ timeout: 10_000 });

        // The copy button renders with text "Copy" or "Copied!"
        await expect(page.getByRole('button', { name: /Copy/i })).toBeVisible();
    });
});

test.describe('Settings — account', () => {
    test('settings page shows the logged-in user email', async ({ page }) => {
        const { email } = await registerUser(page);
        await page.goto('/settings');

        // The page renders the user email in .page-subtitle once /user/me loads
        const emailDisplay = page.locator('.page-subtitle');
        await expect(emailDisplay).toBeVisible({ timeout: 10_000 });
        await expect(emailDisplay).toHaveText(email);
    });

    test('Log out button is present on the settings page', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible({ timeout: 10_000 });
    });

    test('Delete account button is present on the settings page', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.getByRole('button', { name: 'Delete account' })).toBeVisible({ timeout: 10_000 });
    });
});
