import { test, expect } from '@playwright/test';
import { registerUser } from './helpers';

/**
 * Settings page E2E tests — theme switching and household invite code.
 *
 * Each test registers a fresh user so tests are independent and parallelisable.
 *
 * Requires:
 *   docker compose --profile dev up -d
 *   cd frontend && bun run test:e2e
 */

test.describe('Settings — theme', () => {
    test('clicking Dark mode button applies data-theme="dark" to <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page).toHaveTitle(/Settings/i);

        // Click the "Dark" theme button
        const darkBtn = page.locator('button.theme-btn', { hasText: 'Dark' });
        await expect(darkBtn).toBeVisible();
        await darkBtn.click();

        // The settings page sets data-theme on document.documentElement (<html>)
        const html = page.locator('html');
        await expect(html).toHaveAttribute('data-theme', 'dark', { timeout: 5_000 });

        // The Dark button should receive the active modifier class
        await expect(darkBtn).toHaveClass(/theme-btn--active/);
    });

    test('clicking Light mode button applies data-theme="light" to <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        const lightBtn = page.locator('button.theme-btn', { hasText: 'Light' });
        await expect(lightBtn).toBeVisible();
        await lightBtn.click();

        const html = page.locator('html');
        await expect(html).toHaveAttribute('data-theme', 'light', { timeout: 5_000 });

        await expect(lightBtn).toHaveClass(/theme-btn--active/);
    });

    test('clicking System theme button removes data-theme attribute from <html>', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // First switch to dark so there is something to clear
        await page.locator('button.theme-btn', { hasText: 'Dark' }).click();
        const html = page.locator('html');
        await expect(html).toHaveAttribute('data-theme', 'dark', { timeout: 5_000 });

        // Now switch to System
        const systemBtn = page.locator('button.theme-btn', { hasText: 'System' });
        await systemBtn.click();

        await expect(html).not.toHaveAttribute('data-theme', { timeout: 5_000 });
        await expect(systemBtn).toHaveClass(/theme-btn--active/);
    });
});

test.describe('Settings — household invite code', () => {
    test('invite code is displayed after registration', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // The household section should appear because every new user gets a household.
        const inviteCodeValue = page.locator('.invite-code-value');
        await expect(inviteCodeValue).toBeVisible({ timeout: 10_000 });

        // The invite code generated by the backend should not be empty
        const code = await inviteCodeValue.textContent();
        expect(code).toBeTruthy();
        expect((code ?? '').trim().length).toBeGreaterThan(0);
    });

    test('invite code section shows the household name', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        // The household name used during registration was "E2E Household"
        const householdName = page.locator('.household-name');
        await expect(householdName).toBeVisible({ timeout: 10_000 });
        await expect(householdName).toHaveText('E2E Household');
    });

    test('Copy button is present next to the invite code', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        await expect(page.locator('.invite-code-value')).toBeVisible({ timeout: 10_000 });

        const copyBtn = page.locator('button.action-btn--copy', { hasText: 'Copy' });
        await expect(copyBtn).toBeVisible();
    });
});

test.describe('Settings — account', () => {
    test('settings page shows the logged-in user email', async ({ page }) => {
        const { email } = await registerUser(page);
        await page.goto('/settings');

        const emailDisplay = page.locator('.page-subtitle');
        await expect(emailDisplay).toBeVisible({ timeout: 10_000 });
        await expect(emailDisplay).toHaveText(email);
    });

    test('Log out button is present on the settings page', async ({ page }) => {
        await registerUser(page);
        await page.goto('/settings');

        const logoutBtn = page.locator('button.action-btn--logout', { hasText: 'Log out' });
        await expect(logoutBtn).toBeVisible({ timeout: 10_000 });
    });
});
